name: azure bicep deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_SPN_CREDENTIAL }}

      - name: Deploy Resource Group (Subscription Scope)
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region: centralus
          template: ./src/bicep/resourceGroup.bicep
          parameters: ''
          deploymentName: create-resource-group

      - name: Deploy Infrastructure (Resource Group Scope)
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ahtaskrg324  
          template: ./src/bicep/infra.bicep
          parameters: ./src/bicep/infra.parameters.json
          deploymentName: deploy-infra
          failOnStdErr: false
